import sqlite3,pathlib
DB=pathlib.Path(__file__).resolve().parent.parent/'data'/'collector.db'
def connect():
 c=sqlite3.connect(DB,timeout=15,check_same_thread=False); c.row_factory=sqlite3.Row; c.execute('PRAGMA journal_mode=WAL'); c.execute('PRAGMA busy_timeout=10000'); return c
def col(c,t,n,d):
 if n not in [x[1] for x in c.execute(f'PRAGMA table_info({t})')]: c.execute(f'ALTER TABLE {t} ADD COLUMN {n} {d}')
def init():
 c=connect(); c.executescript('''CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY,url TEXT UNIQUE NOT NULL,interval_sec INTEGER NOT NULL DEFAULT 10,enabled INTEGER NOT NULL DEFAULT 1,last_fetch REAL,last_ok REAL,next_fetch REAL,status TEXT DEFAULT 'new',http_status INTEGER,duration_ms INTEGER DEFAULT 0,total INTEGER DEFAULT 0,valid INTEGER DEFAULT 0,invalid INTEGER DEFAULT 0,duplicates INTEGER DEFAULT 0,unique_count INTEGER DEFAULT 0,error TEXT DEFAULT ''); CREATE TABLE IF NOT EXISTS configs(id INTEGER PRIMARY KEY,fingerprint TEXT UNIQUE NOT NULL,kind TEXT NOT NULL,raw TEXT NOT NULL,first_seen REAL,last_seen REAL); CREATE TABLE IF NOT EXISTS source_configs(source_id INTEGER,config_id INTEGER,last_seen REAL,PRIMARY KEY(source_id,config_id)); CREATE TABLE IF NOT EXISTS issues(id INTEGER PRIMARY KEY,source_id INTEGER,seen_at REAL,kind TEXT,code TEXT,raw TEXT,repairable INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS quarantine(id INTEGER PRIMARY KEY,fingerprint TEXT NOT NULL,source_id INTEGER,kind TEXT NOT NULL,raw TEXT NOT NULL,reasons TEXT NOT NULL,first_seen REAL,last_seen REAL,hits INTEGER DEFAULT 1,UNIQUE(fingerprint,source_id)); CREATE TABLE IF NOT EXISTS warnings(id INTEGER PRIMARY KEY,fingerprint TEXT NOT NULL,source_id INTEGER,kind TEXT NOT NULL,code TEXT NOT NULL,message TEXT NOT NULL,raw TEXT NOT NULL,first_seen REAL,last_seen REAL,hits INTEGER DEFAULT 1,UNIQUE(fingerprint,source_id,code)); CREATE TABLE IF NOT EXISTS repairs(id INTEGER PRIMARY KEY,fingerprint TEXT UNIQUE NOT NULL,kind TEXT NOT NULL,raw_original TEXT NOT NULL,raw_repaired TEXT NOT NULL,changes TEXT NOT NULL,created_at REAL NOT NULL); CREATE TABLE IF NOT EXISTS proposals(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,code TEXT NOT NULL,occurrences INTEGER NOT NULL,sample_raw TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'candidate',first_seen REAL,last_seen REAL,UNIQUE(kind,code)); CREATE TABLE IF NOT EXISTS intelligence_events(id INTEGER PRIMARY KEY,fingerprint TEXT,source_id INTEGER,kind TEXT,state TEXT,confidence REAL,engine_version TEXT,details TEXT,seen_at REAL); CREATE TABLE IF NOT EXISTS engine_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at REAL NOT NULL);''')
 c.execute('''CREATE TABLE IF NOT EXISTS recovery_registry(id INTEGER PRIMARY KEY,original_fingerprint TEXT UNIQUE NOT NULL,original_kind TEXT NOT NULL,original_raw TEXT NOT NULL,candidate_fingerprint TEXT NOT NULL,candidate_kind TEXT NOT NULL,candidate_raw TEXT NOT NULL,class TEXT NOT NULL,confidence REAL NOT NULL,validator_ok INTEGER NOT NULL,xray_ok INTEGER NOT NULL,singbox_ok INTEGER NOT NULL,recoverable INTEGER NOT NULL,first_seen REAL NOT NULL,last_seen REAL NOT NULL,hits INTEGER DEFAULT 1)''')
 for n,d in [('raw_count','INTEGER DEFAULT 0'),('new_count','INTEGER DEFAULT 0'),('known_count','INTEGER DEFAULT 0'),('lifetime_seen','INTEGER DEFAULT 0'),('consecutive_errors','INTEGER DEFAULT 0'),('issue_count','INTEGER DEFAULT 0')]: col(c,'sources',n,d)
 c.commit(); c.close()
